version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm