FROM maven:3.8-openjdk-17 as builder
WORKDIR /app
COPY pom.xml .
# Baixar dependências separadamente (melhor para cache)
RUN mvn dependency:go-offline

# Copiar o código fonte e compilar
COPY src ./src
RUN mvn clean package -DskipTests