version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pagamento-network

  pagamentos-api:
    container_name: pagamentos-api
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - pagamento-network

networks:
  pagamento-network:
    driver: bridge